/**
 * Urgency level for clinical card recommendations and referrals.
 */
export type Urgency = "urgent" | "priority" | "routine";

/**
 * Suggested action categories available for PHC workers.
 */
export type SuggestedAction = "beds" | "transport" | "pharmacy" | "expert" | "sos";

/**
 * Agent identifier covering clinical consultation and specific action workflows.
 */
export type AgentId = "clinical" | SuggestedAction;

/**
 * System health status response including API keys and Chroma index availability.
 */
export type Health = {
  ok: boolean;
  chroma_ready: boolean;
  sarvam_key_present: boolean;
  model: string;
  phc: { id: string; name: string; pincode: string; lat: number; lng: number; district: string; state: string };
};

/**
 * Clinical card detailing ICMR-grounded assessment, steps, referral, and references.
 */
export type ClinicalCard = {
  urgency: Urgency;
  assessment: string[];
  diagnosis: { name: string; icd10?: string | null; confidence: number };
  steps: { n: number; title: string; detail: string }[];
  do_nots: string[];
  referral: {
    required: boolean;
    urgency: Urgency;
    destination: string;
    slip: string;
    golden_hour_min?: number | null;
  };
  sources: { n: number; stw_title: string; section: string; quote: string; pdf: string }[];
  suggested_actions: SuggestedAction[];
  disclaimer: string;
  latency_ms: number;
  retrieval: { chunk_count: number; top_score?: number | null };
  fhir_id?: string | null;
  model?: string | null;
};

/**
 * Hospital facility details including ICU and O2 bed availability.
 */
export type Hospital = {
  id: string;
  name: string;
  type: string;
  lat: number;
  lng: number;
  beds_icu: number;
  beds_oxygen: number;
  beds_general: number;
  accepts_nstemi: boolean;
  phone: string;
  notes: string;
  km: number;
  need_beds: number;
};

/**
 * Emergency transport vehicle information.
 */
export type Vehicle = {
  id: string;
  name: string;
  kind: string;
  available: boolean;
  lat: number;
  lng: number;
  eta_min: number;
  phone: string;
  oxygen?: boolean;
  km?: number;
};

/**
 * Real-time dispatch and location tracking data for transport/courier.
 */
export type Track = {
  trip_id: string;
  kind: string;
  vehicle: Vehicle;
  lat: number;
  lng: number;
  eta_min: number;
  status: "enroute" | "arrived" | string;
  polyline: { lat: number; lng: number }[];
  pharmacy?: Pharmacy;
  note?: string;
};

/**
 * Pharmacy record and stock status for prescribed medicines.
 */
export type Pharmacy = {
  id: string;
  name: string;
  kind: "jan_aushadhi" | "private" | string;
  lat: number;
  lng: number;
  phone: string;
  km: number;
  has_all: boolean;
  missing: string[];
  wanted: string[];
  jan_aushadhi: boolean;
  stock: Record<string, boolean>;
};

/**
 * Medical expert available for remote consultation.
 */
export type Expert = {
  id: string;
  name: string;
  specialty: string;
  mode: string;
  availability: "available" | "on_call" | "busy" | string;
  eta_min: number;
  phone: string;
  facility: string;
  km: number;
};

/**
 * Emergency SOS status and notified contacts.
 */
export type SosStatus = {
  id: string;
  reason: string;
  note: string;
  contacts_notified: { id: string; name: string; kind: string; phone: string }[];
  ack: "pending" | "acked" | string;
  eta_min: number;
};

/** Message sent by the PHC worker. */
export type WorkerMsg = { id: string; role: "worker"; text: string };

/** Message responses generated by different agents or system status. */
export type AgentMsg =
  | { id: string; role: "agent"; kind: "clinical"; card: ClinicalCard }
  | { id: string; role: "agent"; kind: "beds"; hospitals: Hospital[]; need: string; note?: string }
  | { id: string; role: "agent"; kind: "transport"; track: Track }
  | { id: string; role: "agent"; kind: "pharmacy"; pharmacies: Pharmacy[]; note: string }
  | { id: string; role: "agent"; kind: "courier"; track: Track }
  | { id: string; role: "agent"; kind: "expert"; experts?: Expert[]; consult?: { status: string; expert: Expert; note: string } }
  | { id: string; role: "agent"; kind: "sos"; sos: SosStatus }
  | { id: string; role: "agent"; kind: "error"; text: string }
  | { id: string; role: "agent"; kind: "info"; text: string };

/** Combined message type representing any turn in the workspace chat thread. */
export type Message = WorkerMsg | AgentMsg;
